Repository SeSAC-Ermes/Epari-frontend, pull requests merged in 2024-11, with the labels that each got.

#9 [FEAT] 사이드바 가이드
  package-lock.json
  package.json
  src/App.jsx
  src/assets/epariLogo.jpg
  src/components/MainContent.jsx
  src/components/Sidebar.jsx
  src/pages/Home.jsx
  src/pages/exam/ExamPage.jsx
Labels: enhancement

#10 [FEAT] LMS 초기화면 구현
  src/App.jsx
  src/components/Sidebar.jsx
  src/components/layout/TopBar.jsx
  src/pages/CourseList.jsx
  src/pages/Home.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
Labels: enhancement

#13 [FEAT] LMS 초기 화면 구현
  src/App.jsx
  src/components/AccountContent.jsx
  src/components/CourseDetailContent.jsx
  src/components/CourseListContent.jsx
  src/components/CurriculumContent.jsx
  src/components/LectureNoticeContent.jsx
  src/components/QnAContent.jsx
  src/components/SignInForm.jsx
  src/components/SignUpForm.jsx
  src/components/layout/Sidebar.jsx
  src/pages/AccountPage.jsx
  src/pages/CourseDetailPage.jsx
  src/pages/CourseListPage.jsx
  src/pages/CurriculumPage.jsx
  src/pages/LectureNoticeListPage.jsx
  src/pages/QnAListPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
  src/pages/exam/ExamPage.jsx
Labels: enhancement

#17 [FEAT] 과제 제출 페이지 추가
  src/App.jsx
  src/components/assignment/AssignmentContainer.jsx
  src/components/assignment/AssignmentDetail.jsx
  src/components/assignment/AssignmentHeader.jsx
  src/components/assignment/AssignmentInstructions.jsx
  src/components/assignment/Header.jsx
  src/pages/CourseList.jsx
  src/pages/assignment/AssignmentPage.jsx
  src/pages/assignment/AssignmentSubmitPage.jsx
  src/pages/exam/ExamPage.jsx
Labels: enhancement

#19 [FIX] 잘못된 import 경로 수정
  src/App.jsx
  src/pages/assignment/AssignmentPage.jsx
  src/pages/assignment/AssignmentSubmitPage.jsx
Labels: bug

#21 [FEAT] Q&A 프론트 화면 구현
  src/App.jsx
  src/components/QnAContent.jsx
  src/components/QnADetailContent.jsx
  src/components/QnAWriteContent.jsx
  src/components/layout/Sidebar.jsx
  src/pages/QnADetailPage.jsx
  src/pages/QnAWritePage.jsx
Labels: enhancement

#24 [FEAT] 과제 출제 페이지 React-Quill을 이용하여 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/assignment/AssignmentContainer.jsx
  src/components/assignment/AssignmentDetail.jsx
  src/components/assignment/AssignmentHeader.jsx
  src/components/assignment/AssignmentInstructions.jsx
  src/components/assignment/Header.jsx
  src/components/assignment/PreviewModal.jsx
  src/components/common/FileUpload.jsx
  src/components/common/QuillEditor.jsx
  src/components/layout/Sidebar.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentPage.jsx
  src/pages/assignment/AssignmentSubmitPage.jsx
Labels: enhancement

#27 [FEAT] 출석 관리 페이지 초안 구현
  src/App.jsx
  src/pages/attendance/AttendanceManagementPage.jsx
  src/pages/attendance/AttendanceRow.jsx
  src/pages/attendance/AttendanceStatusSection.jsx
  src/pages/attendance/AttendanceTable.jsx
  src/pages/attendance/StatCard.jsx
  src/pages/attendance/StatCards.jsx
Labels: enhancement

#26 [FEAT] Q&A 작성/상세 화면 첨부파일 및 댓글 기능 구현
  src/components/QnADetailContent.jsx
  src/components/QnAWriteContent.jsx
Labels: enhancement

#36 [FEAT] 강의 출석부 조회 기능 연동
  src/App.jsx
  src/pages/attendance/AttendanceManagementPage.jsx
  src/pages/attendance/AttendanceRow.jsx
  src/pages/attendance/AttendanceStatusSection.jsx
  src/pages/attendance/AttendanceTable.jsx
  src/pages/attendance/StatCards.jsx
Labels: enhancement

#34 [FEAT] 과제 출제 API 연동 및 Quill 에디터 이미지 업로드 구현
  src/.package-lock.json
  src/components/assignment/hooks/AssignmentAPI.js
  src/pages/assignment/AssignmentCreatePage.jsx
Labels: enhancement

#33 [FEAT] Q&A 화면 개선 및 대시보드 공지 링크 추가
  src/App.jsx
  src/components/CourseListContent.jsx
  src/components/NoticeContent.jsx
  src/components/QnAWriteContent.jsx
  src/components/layout/Sidebar.jsx
  src/pages/NoticeListPage.jsx
Labels: enhancement

#38 [FEAT] 수강생 출석 상태 변경 기능 연동 및 날짜 선택 UI 변경
  src/pages/attendance/AttendanceManagementPage.jsx
  src/pages/attendance/AttendanceStatusSection.jsx
  src/pages/attendance/DateNavigation.jsx
Labels: enhancement

#41 [FEAT] 대쉬보드, 강의 상세 페이지 백엔드 연동
  src/App.jsx
  src/api/lecture/lectureApi.js
  src/components/CourseDetailContent.jsx
  src/components/QnAWriteContent.jsx
  src/components/SignInForm.jsx
  src/components/layout/TopBar.jsx
  src/components/lecture/dashboard/CourseCard.jsx
  src/components/lecture/dashboard/CourseListContent.jsx
  src/components/lecture/dashboard/CurriculumContent.jsx
  src/components/lecture/dashboard/LectureManagementModal.jsx
  src/components/lecture/dashboard/NoticeTable.jsx
  src/components/lecture/dashboard/NoticeTabs.jsx
  src/components/lecture/dashboard/TabButton.jsx
  src/components/lecture/detail/CourseContentTabs.jsx
  src/components/lecture/detail/CourseDetailContent.jsx
  src/components/lecture/detail/CourseHeader.jsx
  src/components/lecture/detail/CourseMaterialsGrid.jsx
  src/components/lecture/detail/InstructorCard.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/lecture/CourseDetailPage.jsx
  src/pages/lecture/CourseList.jsx
  src/pages/lecture/CourseListPage.jsx
  src/pages/lecture/CurriculumPage.jsx
Labels: enhancement

#45 [FEAT] Assginment 전역 Axios API 설정 , Assignment path 지정
  src/App.jsx
  src/api/assignment/AssignmentApi.js
  src/components/assignment/AssignmentDetail.jsx
  src/components/assignment/hooks/AssignmentAPI.js
  src/components/layout/Sidebar.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentDeatilPage.jsx
  src/pages/assignment/AssignmentPage.jsx
Labels: enhancement

#47 [REFACTOR] 배포를 위한 리팩토링
  src/App.jsx
  src/components/layout/Sidebar.jsx
  src/pages/attendance/AttendanceManagementPage.jsx
Labels: enhancement

#49 [FEAT] Assignment 리스트 및 출제 백엔드 연동
  src/api/assignment/AssignmentApi.js
  src/components/assignment/AssignmentDetail.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentPage.jsx
Labels: enhancement

#51 [FIX] import문 Assignment 소문자로 변경
  src/pages/assignment/AssignmentDeatilPage.jsx
Labels: bug

#53 [FEAT] 강의 자료 업로드 구현 및 개선, URL 경로 파라미터 방식으로 수정
  src/App.jsx
  src/api/lecture/CourseFileApi.js
  src/api/lecture/lectureApi.js
  src/auth/AuthContext.jsx
  src/auth/WithAuth.jsx
  src/components/CourseListContent.jsx
  src/components/SignInForm.jsx
  src/components/assignment/AssignmentDetail.jsx
  src/components/auth/RootRedirect.jsx
  src/components/common/QuillConfig.js
  src/components/layout/Sidebar.jsx
  src/components/lecture/dashboard/CourseCard.jsx
  src/components/lecture/dashboard/CourseListContent.jsx
  src/components/lecture/detail/CourseDetailContent.jsx
  src/components/lecture/file/CourseFileContent.jsx
  src/components/lecture/file/CourseFileCreateContent.jsx
  src/components/lecture/file/FileDownloadList.jsx
  src/pages/lecture/CourseFileCreatePage.jsx
  src/pages/lecture/CourseFilePage.jsx
Labels: enhancement

#59 [FEAT] 출석 관리 페이지 출석 전체 선택 기능 구현 및 UI/UX 일부 수정
  src/App.jsx
  src/components/attendance/AttendanceRow.jsx
  src/components/attendance/AttendanceStatusSection.jsx
  src/components/attendance/AttendanceTable.jsx
  src/components/attendance/DateNavigation.jsx
  src/components/attendance/StatCard.jsx
  src/components/attendance/StatCards.jsx
  src/pages/attendance/AttendanceManagementPage.jsx
  src/pages/attendance/AttendanceStatusSection.jsx
  tailwind.config.js
Labels: enhancement

#62 [FEAT] 목록 리스트 항목 추가 및 UI 개선
  src/App.jsx
  src/api/assignment/AssignmentApi.js
  src/components/assignment/AssignmentDetail.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentDetailPage.jsx
  src/utils/DateUtils.js
Labels: enhancement

#67 [REFACTOR] 탑바, 사이드바 리팩토링
  src/App.jsx
  src/components/QnAContent.jsx
  src/components/QnAWriteContent.jsx
  src/components/layout/MainLayout.jsx
  src/components/layout/Sidebar.jsx
  src/components/layout/SimpleLayout.jsx
  src/components/layout/TopBar.jsx
  src/components/lecture/detail/CourseContentTabs.jsx
  src/components/lecture/detail/CourseDetailContent.jsx
  src/components/lecture/file/CourseFileCreateContent.jsx
  src/pages/AccountPage.jsx
  src/pages/LectureNoticeListPage.jsx
  src/pages/NoticeListPage.jsx
  src/pages/QnADetailPage.jsx
  src/pages/QnAListPage.jsx
  src/pages/QnAWritePage.jsx
  src/pages/SignInPage.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentDetailPage.jsx
  src/pages/assignment/AssignmentPage.jsx
  src/pages/attendance/AttendanceManagementPage.jsx
  src/pages/lecture/CourseDetailPage.jsx
  src/pages/lecture/CourseFileArchivePage.jsx
  src/pages/lecture/CourseFileCreatePage.jsx
  src/pages/lecture/CourseFilePage.jsx
  src/pages/lecture/CourseListPage.jsx
  src/pages/lecture/CurriculumPage.jsx
  src/pages/student/MyProgressPage.jsx
  src/pages/student/StudentManagementPage.jsx
Labels: enhancement

#68 [FEAT] 시험 기능 구현을 위한 프론트엔드 컴포넌트 구현
  src/App.jsx
  src/api/course/CourseFileAPI.js
  src/api/course/courseAPI.js
  src/components/CourseNoticeContent.jsx
  src/components/NoticeContent.jsx
  src/components/assignment/AssignmentDetail.jsx
  src/components/course/archive/CourseFileArchiveContent.jsx
  src/components/course/archive/FileArchiveList.jsx
  src/components/course/dashboard/CourseCard.jsx
  src/components/course/dashboard/CourseListContent.jsx
  src/components/course/dashboard/CourseManagementModal.jsx
  src/components/course/dashboard/CurriculumContent.jsx
  src/components/course/dashboard/NoticeTable.jsx
  src/components/course/dashboard/NoticeTabs.jsx
  src/components/course/dashboard/TabButton.jsx
  src/components/course/detail/AssignmentList.jsx
  src/components/course/detail/CourseContentTabs.jsx
  src/components/course/detail/CourseDetailContent.jsx
  src/components/course/detail/CourseHeader.jsx
  src/components/course/detail/CourseMaterialsGrid.jsx
  src/components/course/detail/InstructorCard.jsx
  src/components/course/detail/archive/TodayArchiveList.jsx
  src/components/course/file/CourseFileContent.jsx
  src/components/course/file/CourseFileCreateContent.jsx
  src/components/course/file/FileDownloadList.jsx
  src/components/exam/ExamContainer.jsx
  src/components/exam/ExamCreateContainer.jsx
  src/components/exam/ExamCreateForm.jsx
  src/components/exam/ExamHeader.jsx
  src/components/exam/ExamListItem.jsx
  src/components/layout/Sidebar.jsx
  src/pages/CourseNoticeListPage.jsx
  src/pages/LectureNoticeListPage.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/course/CourseDetailPage.jsx
  src/pages/course/CourseFileArchivePage.jsx
  src/pages/course/CourseFileCreatePage.jsx
  src/pages/course/CourseFilePage.jsx
  src/pages/course/CourseList.jsx
  src/pages/course/CourseListPage.jsx
  src/pages/course/CurriculumPage.jsx
  src/pages/exam/ExamCreatePage.jsx
  src/pages/exam/ExamPage.jsx
Labels: enhancement

#70 [FEAT] 커리큘럼 페이지 구현
  package-lock.json
  package.json
  src/api/curriculum/curriculum.js
  src/components/CurriculumCalendar.jsx
  src/components/course/dashboard/CurriculumContent.jsx
Labels: enhancement

#71 [FEAT] RefreshToken을 이용한 AccessToken 갱신 처리 기능 구현
  src/api/axios.js
Labels: enhancement

#72 [FIX] 다운로드 확장자 문제 해결, 강의 대쉬 보드 프로필 출력, 수강생 관리 페이지 구현
  src/api/axios.js
  src/api/course/CourseFileAPI.js
  src/components/course/archive/CourseFileArchiveContent.jsx
  src/components/course/dashboard/CourseCard.jsx
  src/components/course/dashboard/CourseListContent.jsx
  src/components/course/detail/archive/TodayArchiveList.jsx
  src/components/course/file/FileDownloadList.jsx
  src/components/student/AssignmentSection.jsx
  src/components/student/AttendanceSection.jsx
  src/components/student/ExamSection.jsx
  src/components/student/StudentCard.jsx
  src/components/student/StudentManagementContent.jsx
  src/components/student/StudentSearchBar.jsx
  src/pages/student/StudentManagementPage.jsx
Labels: bug, enhancement

#74 [REFACTOR] 캘런더가 5주 정보를 표시하도록 수정
  src/components/CurriculumCalendar.jsx
Labels: refactoring

#76 [FEAT] 출결 관리 페이지 개선(페이지 이탈 방지, 날짜 선택 기능 등)
  src/components/attendance/AttendanceStatusSection.jsx
  src/components/attendance/DateNavigation.jsx
  src/hooks/usePrompt.js
  src/pages/attendance/AttendanceManagementPage.jsx
Labels: enhancement

#78 [FEAT] 과제 리스트 UI 분리 및 File download 구현
  src/.package-lock.json
  src/api/assignment/AssignmentApi.js
  src/api/assignment/FileApi.js
  src/components/assignment/AssignmentDetail.jsx
  src/components/assignment/hooks/useAssignment.js
  src/components/common/QuillEditor.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentDetailPage.jsx
Labels: enhancement

#80 [FEAT] 이메일 인증 기능 추가 및 회원가입 페이지 수정
  package-lock.json
  package.json
  src/components/SignInForm.jsx
  src/components/SignUpForm.jsx
Labels: enhancement

#83 [FEAT] 수강생 관리 백엔드 연동
  src/api/attendance/attendanceAPI.js
  src/api/course/courseFileAPI.js
  src/api/exam/examAPI.js
  src/components/student/AssignmentSection.jsx
  src/components/student/ExamSection.jsx
  src/components/student/StudentCard.jsx
  src/components/student/StudentManagementContent.jsx
Labels: enhancement

#87 [FIX] 배포 실패로 인한 CourseFileAPI -> courseFileAPI 수정
  src/components/course/archive/CourseFileArchiveContent.jsx
  src/components/course/detail/archive/TodayArchiveList.jsx
  src/components/course/file/CourseFileContent.jsx
  src/components/course/file/CourseFileCreateContent.jsx
  src/components/course/file/FileDownloadList.jsx
Labels: bug

#88 [FEAT] 로그아웃, 비밀번호 찾기/변경 기능 구현
  src/App.jsx
  src/components/SignInForm.jsx
  src/components/SignUpForm.jsx
  src/components/auth/ChangePasswordForm.jsx
  src/components/auth/PasswordValidation.jsx
  src/components/auth/ResetPasswordForm.jsx
  src/components/layout/TopBar.jsx
  src/components/mypage/MyPageContent.jsx
  src/pages/mypage/MyPage.jsx
Labels: enhancement

#91 [FEAT] 과제 제출 및 확인 프론트 구현 및 백엔드 연동
  src/api/assignment/AssignmentApi.js
  src/api/assignment/AssignmentFileApi.js
  src/api/assignment/SubmissionApi.js
  src/api/assignment/SubmissionFileApi.js
  src/components/assignment/AssignmentDetail.jsx
  src/components/assignment/hooks/useAssignment.js
  src/components/assignment/hooks/useFileHandling.js
  src/components/assignment/hooks/useSubmission.js
  src/components/common/FileUpload.jsx
  src/components/common/QuillEditor.jsx
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentDetailPage.jsx
  src/utils/FileDownloadUtils.js
Labels: enhancement

#93 [FEAT] 마이페이지의 프로필 설정 및 강의/수강 이력 조회 기능 구현
  src/components/layout/SimpleLayout.jsx
  src/components/layout/TopBar.jsx
  src/components/mypage/CourseHistory.jsx
  src/components/mypage/MyPageContent.jsx
  src/components/mypage/UserProfile.jsx
  src/pages/mypage/MyPage.jsx
Labels: enhancement

#95 [FEAT] 시험 문제 백엔드 연동
  src/App.jsx
  src/api/exam/examAPI.js
  src/components/assignment/hooks/useFileHandling.js
  src/components/auth/ResetPasswordForm.jsx
  src/components/course/dashboard/CourseCard.jsx
  src/components/course/detail/CourseDetailContent.jsx
  src/components/course/detail/ExamAssignmentSection.jsx
  src/components/course/detail/archive/TodayArchiveList.jsx
  src/components/exam/ExamBasicSettings.jsx
  src/components/exam/ExamContainer.jsx
  src/components/exam/ExamCreateForm.jsx
  src/components/exam/ExamDetail.jsx
  src/components/exam/ExamEdit.jsx
  src/components/exam/ExamListItem.jsx
  src/components/exam/ExamQuestions.jsx
  src/components/exam/ExamSubmission.jsx
  src/components/layout/TopBar.jsx
  src/components/mypage/MyPageContent.jsx
  src/components/student/StudentManagementContent.jsx
  src/constants/auth.js
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/exam/ExamBasicSettingsPage.jsx
  src/pages/exam/ExamCreatePage.jsx
  src/pages/exam/ExamDetailPage.jsx
  src/pages/exam/ExamEditPage.jsx
  src/pages/exam/ExamPage.jsx
  src/pages/exam/ExamQuestionPage.jsx
  src/pages/exam/ExamSubmissionPage.jsx
Labels: enhancement

#99 [REFACTOR] 학생 시험 조회시 불필요한 정보 제거
  src/components/exam/ExamContainer.jsx
  src/components/exam/ExamDetail.jsx
Labels: refactoring

#100 [REFACTOR] 수강생 관리에서 출석 관리 페이지 이동 구현 및 권한 인증 구현
  src/components/attendance/AttendanceStatusSection.jsx
  src/components/student/StudentCard.jsx
  src/components/student/StudentManagementContent.jsx
  src/constants/auth.js
  src/pages/course/CourseFileCreatePage.jsx
  src/pages/student/StudentManagementPage.jsx
Labels: refactoring

#101 [FEAT] 과제 채점 및 피드백 페이지 구현
  src/App.jsx
  src/api/assignment/SubmissionApi.js
  src/components/assignment/AssignmentDetail.jsx
  src/components/assignment/SubmissionList.jsx
  src/components/assignment/hooks/useAssignment.js
  src/components/assignment/hooks/useSubmission.js
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentDetailPage.jsx
  src/pages/assignment/SubmissionListPage.jsx
Labels: enhancement

#107 [FEAT] 시험별 학생 성적 및 답안 확인 화면 구현
  src/App.jsx
  src/api/exam/examAPI.js
  src/components/exam/ExamBasicSettings.jsx
  src/components/exam/ExamContainer.jsx
  src/components/exam/ExamCreateContainer.jsx
  src/components/exam/ExamDetail.jsx
  src/components/exam/ExamEdit.jsx
  src/components/exam/ExamHeader.jsx
  src/components/exam/ExamListItem.jsx
  src/components/exam/ExamQuestions.jsx
  src/components/exam/ExamResults.jsx
  src/components/exam/ExamSubmission.jsx
  src/pages/exam/ExamBasicSettingsPage.jsx
  src/pages/exam/ExamDetailPage.jsx
  src/pages/exam/ExamEditPage.jsx
  src/pages/exam/ExamPage.jsx
  src/pages/exam/ExamQuestionPage.jsx
  src/pages/exam/ExamSubmissionPage.jsx
Labels: enhancement

#111 [FIX] 시험 결과 조회 Axios 관련 수정
  src/components/exam/ExamListItem.jsx
  src/components/exam/ExamResults.jsx
Labels: bug

#110 [FEAT] 공지사항 CRUD 기능을 프론트(React) 연동
  src/App.jsx
  src/api/notice/NoticeApi.js
  src/components/CourseNoticeContent.jsx
  src/components/NoticeContent.jsx
  src/components/course/dashboard/CourseListContent.jsx
  src/components/course/dashboard/NoticeTable.jsx
  src/components/course/detail/CourseDetailContent.jsx
  src/components/layout/Sidebar.jsx
  src/components/notice/NoticeContent.jsx
  src/components/notice/NoticeDetailContent.jsx
  src/components/notice/NoticeEditContent.jsx
  src/components/notice/NoticeListContent.jsx
  src/components/notice/NoticeWriteContent.jsx
  src/components/qna/QnAContent.jsx
  src/components/qna/QnADetailContent.jsx
  src/components/qna/QnAWriteContent.jsx
  src/constants/auth.js
  src/pages/CourseNoticeListPage.jsx
  src/pages/NoticeListPage.jsx
  src/pages/notice/CourseNoticeListPage.jsx
  src/pages/notice/NoticeDetailPage.jsx
  src/pages/notice/NoticeListPage.jsx
  src/pages/notice/NoticeWritePage.jsx
  src/pages/qna/QnADetailPage.jsx
  src/pages/qna/QnAListPage.jsx
  src/pages/qna/QnAWritePage.jsx
Labels: enhancement

#113 [REVERT] "[FEAT] 공지사항 CRUD 기능을 프론트(React) 연동"
  src/App.jsx
  src/api/notice/NoticeApi.js
  src/components/CourseNoticeContent.jsx
  src/components/NoticeContent.jsx
  src/components/QnAContent.jsx
  src/components/QnADetailContent.jsx
  src/components/QnAWriteContent.jsx
  src/components/course/dashboard/CourseListContent.jsx
  src/components/course/dashboard/NoticeTable.jsx
  src/components/course/detail/CourseDetailContent.jsx
  src/components/layout/Sidebar.jsx
  src/components/notice/NoticeContent.jsx
  src/components/notice/NoticeDetailContent.jsx
  src/components/notice/NoticeEditContent.jsx
  src/components/notice/NoticeListContent.jsx
  src/components/notice/NoticeWriteContent.jsx
  src/constants/auth.js
  src/pages/CourseNoticeListPage.jsx
  src/pages/NoticeListPage.jsx
  src/pages/QnADetailPage.jsx
  src/pages/QnAListPage.jsx
  src/pages/QnAWritePage.jsx
  src/pages/notice/CourseNoticeListPage.jsx
  src/pages/notice/NoticeDetailPage.jsx
  src/pages/notice/NoticeListPage.jsx
  src/pages/notice/NoticeWritePage.jsx
Labels: bug

#112 [FEAT] 과제 미제출 학생포함 리스트 조회 구현
  src/components/assignment/SubmissionList.jsx
  src/utils/DateUtils.js
Labels: enhancement

#115 [REFACTOR] 미제출 학생 포함 조회
  src/components/assignment/SubmissionList.jsx
Labels: refactoring

#118 Google Auth2 소셜 로그인 구현
  package-lock.json
  package.json
  src/App.jsx
  src/auth/AuthContext.jsx
  src/auth/RootRedirect.jsx
  src/components/SignInForm.jsx
  src/components/SignUpForm.jsx
  src/components/common/button/GoogleLoginButton.jsx
  src/config/amplify-config.js
  src/main.jsx
  src/pages/auth/PendingApprovalPage.jsx
Labels: enhancement

#122 FIX: 로고 위치 변경
  src/components/SignInForm.jsx
  src/components/SignUpForm.jsx
  src/components/auth/NewPasswordForm.jsx
  src/components/auth/ResetPasswordForm.jsx
  src/components/layout/TopBar.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
Labels: bug

#125 [FIX] OAuth 리디렉션 URL 환경 설정 오류 수정
  src/config/amplify-config.js
Labels: enhancement

#120 [MERGE] 병합 충돌 해결
  src/App.jsx
  src/api/notice/NoticeApi.js
  src/components/course/dashboard/CourseListContent.jsx
  src/components/course/dashboard/NoticeTable.jsx
  src/components/course/detail/CourseDetailContent.jsx
  src/components/layout/Sidebar.jsx
  src/components/notice/NoticeContent.jsx
  src/components/notice/NoticeDetailContent.jsx
  src/components/notice/NoticeEditContent.jsx
  src/components/notice/NoticeListContent.jsx
  src/components/notice/NoticeWriteContent.jsx
  src/components/qna/QnAContent.jsx
  src/components/qna/QnADetailContent.jsx
  src/components/qna/QnAWriteContent.jsx
  src/pages/QnADetailPage.jsx
  src/pages/notice/NoticeDetailPage.jsx
  src/pages/notice/NoticeListPage.jsx
  src/pages/notice/NoticeWritePage.jsx
  src/pages/qna/QnADetailPage.jsx
  src/pages/qna/QnAListPage.jsx
  src/pages/qna/QnAWritePage.jsx
Labels: bug

#128 [REFACTOR] 시험 출제 및 응시 양식 수정, 컴포넌트 구조 나누기
  src/App.jsx
  src/components/exam/ExamCreateContainer.jsx
  src/components/exam/ExamHeader.jsx
  src/components/exam/ExamQuestions.jsx
  src/components/exam/ExamSubmission.jsx
  src/components/exam/creation/ExamBasicSettings.jsx
  src/components/exam/creation/ExamQuestions.jsx
  src/components/exam/creation/ImageUploade.jsx
  src/components/exam/creation/QuestionCard.jsx
  src/components/exam/creation/UploadGuide.jsx
  src/components/exam/details/ExamDetail.jsx
  src/components/exam/grading/ExamGradingForm.jsx
  src/components/exam/grading/ExamGradingList.jsx
  src/components/exam/management/ExamContainer.jsx
  src/components/exam/management/ExamEdit.jsx
  src/components/exam/management/ExamListItem.jsx
  src/components/exam/results/ExamResults.jsx
  src/components/exam/results/StudentExamResultContent.jsx
  src/components/exam/submission/ExamSubmission.jsx
  src/components/exam/submission/ExamSubmissionHeader.jsx
  src/components/exam/submission/ExamSubmissionNavigation.jsx
  src/components/exam/submission/ExamSubmissionQuestionCard.jsx
  src/components/exam/submission/ExamSubmissionQuestionList.jsx
  src/components/exam/submission/ExamSubmissionStartScreen.jsx
  src/components/layout/Sidebar.jsx
  src/components/notice/NoticeContent.jsx
  src/components/notice/NoticeDetailContent.jsx
  src/components/notice/NoticeEditContent.jsx
  src/components/notice/NoticeListContent.jsx
  src/components/notice/NoticeWriteContent.jsx
  src/components/qna/QnADetailContent.jsx
  src/pages/ExamResultPage.jsx
  src/pages/exam/ExamBasicSettingsPage.jsx
  src/pages/exam/ExamDetailPage.jsx
  src/pages/exam/ExamEditPage.jsx
  src/pages/exam/ExamGradingFormPage.jsx
  src/pages/exam/ExamGradingListPage.jsx
  src/pages/exam/ExamPage.jsx
  src/pages/exam/ExamQuestionPage.jsx
  src/pages/exam/ExamSubmissionPage.jsx
  src/pages/exam/StudentExamResultPage.jsx
  src/pages/qna/QnAWritePage.jsx
Labels: enhancement, refactoring

#130 [FEAT] 공지사항 첨부파일 다운로드 구현
  src/api/notice/NoticeApi.js
  src/components/notice/NoticeDetailContent.jsx
  src/components/notice/NoticeEditContent.jsx
  src/components/notice/NoticeWriteContent.jsx
Labels: enhancement

#129 [FEAT] Google 계정 사용자 프로필 Google 프로필 사진 연동
  src/auth/AuthContext.jsx
  src/auth/RootRedirect.jsx
  src/components/layout/TopBar.jsx
  src/components/mypage/MyPageContent.jsx
  src/components/mypage/UserProfile.jsx
  src/config/amplify-config.js
Labels: enhancement

#134 [FEAT] 강의 자료실, 강의 학습 활동 무한 스크롤, 검색 백엔드 연동
  src/api/course/courseFileAPI.js
  src/components/course/archive/CourseFileArchiveContent.jsx
  src/components/course/archive/FileArchiveList.jsx
  src/components/course/file/CourseFileContent.jsx
  src/components/course/file/CourseFileEditForm.jsx
Labels: enhancement

#133 [REFACTOR] RoleBasedComponent 리팩토링
  src/api/assignment/AssignmentApi.js
  src/api/assignment/SubmissionApi.js
  src/components/assignment/AssignmentDetail.jsx
Labels: refactoring

#137 [FEAT] 강의 자료 조회 오프셋 기반 페이지네이션 적용 페이지 구현
  src/App.jsx
  src/api/course/courseFileAPI.js
  src/components/course/file/CourseFileOffsetContent.jsx
Labels: enhancement

#139 [REFACTOR] withPageAuth 사용하여 권한 별 접근 차단
  src/constants/auth.js
  src/pages/assignment/AssignmentCreatePage.jsx
  src/pages/assignment/AssignmentDetailPage.jsx
  src/pages/assignment/AssignmentPage.jsx
  src/pages/assignment/SubmissionListPage.jsx
Labels: refactoring
