Repository SeSAC-Ermes/Epari-frontend, pull requests merged in 2025-01, with the labels that each got.

#147 [FIX] Lambda 트리거를 활용한 사용자 그룹 할당 및 라우팅 로직 개선
  src/components/common/button/GoogleLoginButton.jsx
Labels: bug, enhancement

#150 [REFACTOR] 백엔드 엔드포인트 변경에 따른 API 경로 변경
  src/api/exam/examAPI.js
  src/components/exam/results/ExamResults.jsx
Labels: refactoring

#151 [FEAT] 구글 계정 사용 시 '일반 회원가입' 및 '일반 로그인' 처리 로직 개선
  src/components/SignInForm.jsx
  src/components/SignUpForm.jsx
Labels: enhancement

#152 [FEAT] 게시판 연동을 위한 작업
  package-lock.json
  package.json
  src/App.jsx
  src/components/board/BoardDetailContent.jsx
  src/components/board/BoardListContent.jsx
  src/components/board/BoardWriteContent.jsx
  src/components/board/CategoryFilter.jsx
  src/components/board/CategorySlider.jsx
  src/components/board/CommentItem.jsx
  src/components/board/PostCard.jsx
  src/components/board/SearchBar.jsx
  src/components/board/TagSearch.jsx
  src/components/board/TrendingPosts.jsx
  src/components/editor/EditorTabs.jsx
  src/components/editor/TagInput.jsx
  src/components/editor/TinyEditor.jsx
  src/components/editor/ToastEditor.jsx
  src/components/layout/TopBar.jsx
  src/main.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardListPage.jsx
  src/pages/board/BoardWritePage.jsx
  vite.config.js
Labels: enhancement

#154 [FIX] 젠킨스 빌드 오류 해결
  package-lock.json
  package.json
Labels: bug

#156 [FIX] JSON 응답 대신 HTML 문서를 받아서 발생하는 문제 해결
  src/api/boardAxios.js
  src/components/board/BoardDetailContent.jsx
  src/components/board/BoardListContent.jsx
  src/components/board/BoardWriteContent.jsx
  src/components/board/CategoryFilter.jsx
  src/components/board/PostCard.jsx
  src/components/board/TagSearch.jsx
  src/components/board/TrendingPosts.jsx
  src/components/editor/TinyEditor.jsx
  vite.config.js
Labels: bug

#158 [CHORE] API Gateway 엔드포인트 변경
  src/api/boardAxios.js
  vite.config.js
Labels: bug

#160 [FEAT] 커뮤니티 AI 챗봇 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/board/ChatbotInterface.jsx
  src/components/board/ChatbotInterfaceLegacy.jsx
  src/components/layout/ChatbotLayout.jsx
Labels: enhancement

#161 [FIX] 코그니토 user name 처리 이슈 해결
  src/assets/default-avatar.jpg
  src/components/board/BoardDetailContent.jsx
  src/components/board/BoardWriteContent.jsx
  src/components/board/CommentItem.jsx
Labels: bug

#163 [FIX] 사용자 이름 업데이트 안되는 이슈 해결
  src/api/boardAxios.js
  src/components/board/BoardDetailContent.jsx
  src/components/board/BoardListContent.jsx
  src/components/board/BoardWriteContent.jsx
  src/components/board/CommentItem.jsx
Labels: bug

#165 [REFACTOR] 게시판 댓글 프로필 이미지 수정
  src/components/board/CommentItem.jsx
Labels: refactoring

#167 [FIX] 본인 게시글 수정 삭제 안되는 현상 해결
  src/components/board/BoardDetailContent.jsx
Labels: bug
